kind: ReplicaSet
apiVersion: extensions/v1beta1
metadata:
  name: centos-ssh
  namespace: jgl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: centos-ssh
    spec:
      containers:
        - name: centos-ssh
          image: guiljin/ssh:centos7
          ports:
            - containerPort: 22
              hostPort: 65533
              protocol: TCP
          command: ["/usr/sbin/sshd","-D"]
# root:password